# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder "..", "/home/vagrant/ansible-elk"
  
  config.vm.hostname = "elk.local"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network :private_network, ip: "192.168.3.10"
  config.hostsupdater.remove_on_suspend = true
  config.hostsupdater.aliases = ["alias.elk.local"]


  config.vm.provider :virtualbox do |vb|
  	vb.customize ["modifyvm", :id, "--name", "elk", "--memory", "2048"]
  end

  config.vm.provision "ansible" do |ansible|
  	ansible.playbook = "vagrant.yml"
  	ansible.host_key_checking = false
  	ansible.verbose = "v"
  end

end
