---

- name: Add Elasticsearch repository public key
  apt_key: url={{ elasticsearch.public_key }}
  tags:
    - elasticsearch

- name: Add Elasticsearch repository
  apt_repository: repo={{ elasticsearch.repository }} state=present
  tags:
    - elasticsearch

- name: Install Elasticsearch
  apt: name=elasticsearch update_cache=yes
  tags:
    - elasticsearch

- name: Register Elasticsearch in init.d
  command: update-rc.d elasticsearch defaults 95 10
  tags:
      - elasticsearch

- name: Enable and start Elasticsearch
  service: name=elasticsearch enabled=yes state=started
  tags:
    - elasticsearch

# TODO: Install config template